### ISSUE TITLE
UglifyJs ERROR

### ISSUE THREAD

**Issue by feusebio** [lyollix/vue-slideout-panel#1]
I try use the component VUE in my app, but i can't build the project:
> Version: webpack 3.3.0 
ERROR in static/js/vendor.js from UglifyJs
Unexpected token: name (c) [./node_modules/vue-slideout-panel/dist/index.js:1,4519][static/js/vendor.js:20001,4479]

Thanks for the component, it's a great job!

**Comment by feusebio** [comment]
Good news, i did a build internal in the component, and "voilá" the  ERROR in build at my app was gone.

Thanks

**Comment by kubmin** [comment]
Hi there!

What do you mean by this? Currently facing the exact same problem when building and I would love to know how you fixed this!

EDIT: Fixed it! 

navigate to the node_modules folder into the vue-slideout-panel, install 'babili-webpack-plugin' by running `npm install babili-webpack-plugin`. After that has been installed run `npm run build`.

Finally navigate back to your Vue app and run `npm run build`. This fixed it for me.

Cheers!
